CREATE SERVER AUDIT SPECIFICATION Clinic_ServerAuditSpec
FOR SERVER AUDIT Clinic_Audit
ADD (SUCCESSFUL_LOGIN_GROUP),
ADD (FAILED_LOGIN_GROUP),
ADD (LOGOUT_GROUP);
ALTER SERVER AUDIT SPECIFICATION Clinic_ServerAuditSpec WITH (STATE = ON);