USE MedixCareDB;
CREATE DATABASE AUDIT SPECIFICATION Clinic_DB_AuditSpec
FOR SERVER AUDIT Clinic_Audit
ADD (DATABASE_PERMISSION_CHANGE_GROUP),
ADD (BACKUP_RESTORE_GROUP),
ADD (INSERT, UPDATE, DELETE ON Patients BY PUBLIC);
ALTER DATABASE AUDIT SPECIFICATION Clinic_DB_AuditSpec WITH (STATE = ON);